<?php
/**
 * Created by PhpStorm.
 * User: Muhammad Abubakar
 * Date: 4/13/2018
 * Time: 1:19 PM
 */

return [
    'IMAGE_URL' => 'uploads/files/Image/',
    'BRANDS' => [
        'Honda', 'Yamaha', 'Suzuki', 'Super Power', 'Chinese Bikes',
        'United',
        'Unique',
        'Kawasaki',
        'More Brands',
        'Road Prince',
        'Aprilia',
        'Asia Hero',
        'BML','BMW',
        'BSA',
        'Benelli',
        'Blue Star',
        'Can-am spyder',
        'Crown',
        'DYL',
        'Derbi',
        'Diamond',
        'Ducati',
        'Eagle',
        'FUEGO',
        'Ghani',
        'Habib',
        'Davidson',
        'Hero',
        'Hi Speed',
        'KEEWAY',
        'Lifan',
        'Loncin',
        'Metro',
        'OVERDRIVE',
        'Pak Hero',
        'Power',
        'Prince',
        'QINGQI',
        'Ravi',
        'Razy Motors',
        'Sigma',
        'Sohrab',
        'Super Asia',
        'Super Speed',
        'Super Star',
        'Supreme',
        'Toyo',
        'Treet',
        'Triumph',
        'U.M',
        'Union Star',
        'Vespa',
        'ZXMCO',
        'Zongshen',
        'Other',
    ],
    'CITIES' => [
        'Lahore',
'Karachi',
'Rawalpindi',
'Islamabad',
'Peshawar',
'Quetta',
'Abdul Hakeem',
'Abottabad',
'Ahmed Pur East',
'Arifwala',
'Attock',
'Bahawal Nagar',
'Bahawalpur',
'Balakot',
'Bannu',
'Bhakkar',
'Bhalwal',
'Bhimber',
'Burewala',
'Chakwal',
'Charsadda',
'Chichawatni',
'Chiniot',
'D.G.Khan',
'Dadyal Ak',
'Daska',
'Depal pur',
'Dera ismail khan',
'Dina',
'Dinga',
'Faisalabad',
'Fateh Jang',
'Gojra',
'Gujar Khan',
'Gujranwala',
'Gujrat',
'Hafizabad',
'Hangu',
'Hari pur',
'Haroonabad',
'Hassan abdal',
'Hyderabad',
'Jahaniya',
'Jalalpur Jattan',
'Jauharabad',
'Jehlum',
'Jhang',
'Kahuta',
'Kallur kot',
'Kamra',
'Karak',
'Kashmir',
'Kasur',
'Khairpur',
'Khanewal',
'Kharian',
'Khushab',
'Kohat',
'Kotla arab ali khan',
'Lala musa',
'Larkana',
'Layyah',
'Mandi bahauddin',
'Mansahra',
'Mardan',
'Mian Channu',
'Mian Wali',
'Mirpur A.K.',
'Multan',
'Muzaffar Gargh',
'Muzaffarabad',
'Nankana sahib',
'Narowal',
'Nawabshah',
'Nowshera',
'Okara',
'Pattoki',
'Phalia',
'Pind Dadan Khan',
'Quaid Abad',
'Rahim Yar Khan',
'Rawala kot',
'Sadiqabad',
'Sahiwal',
'Sargodha',
'Sawabi',
'Shahdara',
'Shaikhupura',
'Shiekhopura',
'Sialkot',
'Sillanwali',
'Sukkur',
'Swat',
'Talagang',
'Tando adam',
'Taxila',
'Toba Tek Singh',
'Vehari',
'Wah cantt',
'Warburton']
];
